package com.example.gieterp

object AppSession {
    const val PREFERENCES_NAME = "MyPrefs"
    const val KEY_ROLL_NO = "rollno"
    const val KEY_STUDENT_ID = "studentId"
    const val KEY_PUSH_TOKEN = "pushToken"
    const val KEY_PUSH_TOKEN_ROLL_NO = "pushTokenRollNo"
    const val KEY_LAST_ATTENDANCE_EVENT_ID = "lastAttendanceEventId"
    const val KEY_NOTIFICATION_PERMISSION_REQUESTED = "notificationsPermissionRequested"
    const val KEY_INSTALL_ID = "installId"
    const val KEY_INSTALL_REGISTERED = "installRegistered"
    const val KEY_APP_CONTROL_ENABLED = "appControlEnabled"
    const val KEY_APP_CONTROL_MESSAGE = "appControlMessage"
    const val KEY_APP_CONTROL_UPDATED_AT = "appControlUpdatedAt"
    const val KEY_APP_CONTROL_UPDATED_BY = "appControlUpdatedBy"

    const val EXTRA_ATTENDANCE_RESPONSE = "response"
    const val EXTRA_EXAM_ID = "examId"
    const val EXTRA_STUDENT_ID = "studentId"
    const val EXTRA_OVERRIDE_ROLL_NO = "overrideRollNo"
    const val EXTRA_OVERRIDE_STUDENT_NAME = "overrideStudentName"
    const val EXTRA_OVERRIDE_INITIAL_SEMESTER = "overrideInitialSemester"
    const val EXTRA_OVERRIDE_MAX_SEMESTER = "overrideMaxSemester"
    const val EXTRA_OPEN_ATTENDANCE_FROM_NOTIFICATION = "openAttendanceFromNotification"
    const val EXTRA_ATTENDANCE_EVENT_ID = "attendanceEventId"
    const val EXTRA_ATTENDANCE_SUBJECT = "attendanceSubject"
    const val EXTRA_ATTENDANCE_STATUS = "attendanceStatus"
    const val EXTRA_ATTENDANCE_SEMESTER = "attendanceSemester"
}
